In [1]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.rand(5)

array([0.01938395, 0.72659115, 0.66396432, 0.98593426, 0.49011878])

In [21]:
np.random.rand(5,5)

array([[0.39814129, 0.17630835, 0.60364696, 0.45572232, 0.76973094],
       [0.87617983, 0.56297998, 0.42909229, 0.6188535 , 0.23669139],
       [0.69138008, 0.15342966, 0.20875004, 0.67775183, 0.26257232],
       [0.31674459, 0.85062233, 0.13437704, 0.55686686, 0.2856566 ],
       [0.07684162, 0.51468397, 0.29275751, 0.82114146, 0.79680052]])

In [22]:
np.random.randn(2)

array([-1.0820985 ,  1.53186212])

In [23]:
np.random.randn(4,4)

array([[ 0.95134349, -0.70831558, -0.32062999, -0.67979181],
       [ 0.89857193,  0.10880114, -1.34100619,  0.66700553],
       [ 0.06859483,  1.09730194,  0.88746222,  1.56215956],
       [ 0.52323581,  1.28456986, -0.77314964, -1.9082731 ]])

In [31]:
np.random.randint(1,100,5)

array([37, 31, 15, 81, 53], dtype=int32)

In [26]:
arr = np.arange(25)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
ranarr = np.random.randint(0,50,10)

In [44]:
ranarr

array([21,  5, 39, 24,  7, 26,  5, 34,  9, 35], dtype=int32)

In [45]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
ranarr.max()

np.int32(39)

In [47]:
ranarr.min()

np.int32(5)

In [48]:
ranarr.argmax()

np.int64(2)

In [49]:
ranarr.argmin()

np.int64(1)

In [51]:
arr = arr.reshape(5,5)

In [53]:
arr.shape

(5, 5)

In [54]:
arr.dtype

dtype('int64')

In [55]:
from numpy.random import randint

In [56]:
randint(2,10)

4