In [1]:
import numpy as np

In [5]:
arr = np.arange(0,11)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[8]

8

In [9]:
arr[1:5]

array([1, 2, 3, 4])

In [10]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [11]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [12]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [13]:
arr[0:5] = 100

In [14]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [15]:
arr = np.arange(0,11)

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
slice_of_arr = arr[0:6]

In [18]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [19]:
slice_of_arr[:] = 99

In [20]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [21]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
arr_copy = arr.copy()

In [23]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [24]:
arr_copy[:] = 100

In [25]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [26]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

--numpy indexing and selection on matrices

In [28]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [29]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [33]:
arr_2d[2][1]

np.int64(40)

In [34]:
arr_2d[1,2]

np.int64(30)

In [37]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [38]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [39]:
arr_2d[1:,0:]

array([[20, 25, 30],
       [35, 40, 45]])

In [40]:
#conditional selection

In [41]:
arr = np.arange(1,11)

In [42]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
bool_arr = arr > 5

In [45]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [46]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [47]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [48]:
arr[arr<3]

array([1, 2])

In [49]:
arr_2d = np.arange(50).reshape(5,10)

In [50]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [51]:
# Grab 13,14 and 23,24

In [52]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [53]:
#Practices: Grab 37,38,39 and 47,48,49

In [54]:
arr_2d[3:,7:]

array([[37, 38, 39],
       [47, 48, 49]])

In [55]:
#Practices: Grab 1,2,3 and 11,12,13 and 21,22,23

In [56]:
arr_2d[:3,1:4]

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23]])